chore: sync upstream
Log:

diff --git a/prime-select b/prime-select
--- a/prime-select
+++ b/prime-select
@@ -17,7 +17,7 @@ xorg_amd_conf="/usr/share/prime/xorg-amd.conf"
 xorg_nvidia_prime_render_offload="/usr/share/prime/xorg-nvidia-prime-render-offload.conf"
 prime_logfile="/var/log/prime-select.log"
 nvidia_modules="nvidia_drm nvidia_modeset nvidia_uvm nvidia"
-driver_choices="nvidia|intel|amd|offload"
+driver_choices="nvidia|intel|intel2|amd|offload"
 lspci_intel_line="VGA compatible controller: Intel"
 lspci_amd_line="VGA compatible controller: Advanced Micro Devices"
 lspci_nvidia_vga_line="VGA compatible controller: NVIDIA"
@@ -66,14 +66,16 @@ function usage {
         echo "usage: $(basename $0) next-boot $driver_choices|abort"
         echo "usage: $(basename $0) service   check|disable|restore"
     else
-        echo "usage: $(basename $0) $driver_choices|unset|get-current|log-view|log-clean"
+        echo "usage: $(basename $0) $driver_choices|unset|get-current|offload-set|log-view|log-clean"
     fi
 
     echo
     echo "nvidia:      use the NVIDIA proprietary driver"
     echo "intel:       use the Intel card with the \"modesetting\" driver"
-    echo "amd:         use the Amd card with the \"modesetting\" driver"
+    echo "intel2:      use the Intel card with the \"intel\" Open Source driver (xf86-video-intel)"
+    echo "amd:         use the Amd card with the \"amd\" Open Source driver (xf86-video-amdgpu)"
     echo "offload      PRIME Render Offload possible with >= 435.xx NVIDIA driver"
+    echo "offload-set  choose which intel driver use in PRIME Render Offload"
     echo "unset:       disable effects of this script and let Xorg decide what driver to use"
     echo "get-current: display driver currently configured"
     echo "log-view:    view logfile"
@@ -121,7 +123,7 @@ function check_service {
 
 function nv_offload_capable {
     #checks if nvidia driver version is offload capable (>=435.00)
-    (( $(modinfo nvidia-current | grep ^version: | awk '{print $2}' | tr -d .) >= 43500 ))
+    (( $(modinfo nvidia | grep ^version: | awk '{print $2}' | tr -d .) >= 43500 ))
 }
 
 function offload_pref_check {
@@ -178,7 +180,7 @@ function nvpwr {
         fi
     else
         if ! lsmod | grep bbswitch > /dev/null; then
-            modprobe bbswitch load_state=0 unload_state=1 > /dev/null 2>&1
+            modprobe bbswitch load_state=0 unload_state=1
         else
             #should never happens
             tee /proc/acpi/bbswitch <<<OFF
@@ -195,7 +197,35 @@ function clean_xorg_conf_d {
 }
 
 function update_kdeglobals {
-    return
+
+    # The KDE kscreen5 module ('Display and Monitor' settings) stores the user-defined scaling for all detected monitors
+    # in file ~/.config/kdeglobals, in the ScreenScaleFactors line. For example:
+    #
+    # ScreenScaleFactors=eDP-1-1=2;DP-0=2;DP-1=2;HDMI-0=2;DP-2=2;DP-3=2;DP-4=2;
+    #
+    # /usr/bin/startkde reads this value and assigns it to environment variable QT_SCREEN_SCALE_FACTORS:
+    #
+    # QT_SCREEN_SCALE_FACTORS=eDP-1-1=2;DP-0=2;DP-1=2;HDMI-0=2;DP-2=2;DP-3=2;DP-4=2;
+    #
+    # The value of this variable is crucial to have KDE scale the QT widgets properly
+    #
+    # The problem is that the laptop panel output name (eDP-1-1 in that example, always listed first) is not the same depending
+    # on whether the intel (modesetting), intel2 (intel) or nvidia driver is used, resulting in that variable
+    # not being up-to-date when user switches drivers with this script and scaling not working properly
+    #
+    # code below is a workaround that edits file ~/.config/kdeglobals with the proper panel name
+    # passed as first parameter of this function
+
+    [ -z "$user" ] && return
+
+    panel_name=${1}
+
+    kdeglobals="$(sudo -u $user /usr/bin/printenv HOME)/.config/kdeglobals"
+
+    if [ -f $kdeglobals ]; then
+        sudo -u $user sed -i -r "s/(ScreenScaleFactors=)$panel_nvidia|$panel_intel|$panel_intel2/\1$panel_name/" "$kdeglobals"
+        logging "updated $kdeglobals"
+    fi
 }
 
 function restore_old_state {
@@ -256,10 +286,10 @@ function set_nvidia {
 
     nvidia_busid=$(echo "$gpu_info" | grep -i "PCI BusID" | head -n 1 | sed 's/PCI BusID ://' | sed 's/ //g')
 
-    #if [ -f /usr/lib*/xorg/modules/extensions/nvidia/nvidia-libglx.so ]; then
-    #    libglx_nvidia=$(update-alternatives --list libglx.so|grep nvidia-libglx.so)
-    #    update-alternatives --set libglx.so $libglx_nvidia > /dev/null
-    #fi
+    if [ -f /usr/lib*/xorg/modules/extensions/nvidia/nvidia-libglx.so ]; then
+        libglx_nvidia=$(update-alternatives --list libglx.so|grep nvidia-libglx.so)
+        update-alternatives --set libglx.so $libglx_nvidia > /dev/null
+    fi
 
     clean_xorg_conf_d
 
@@ -302,18 +332,19 @@ function set_amd {
 
 }
 
+
 function common_set {
     # find Intel card bus id. Without this Xorg may fail to start
     lspci_line=$1
     constructor=$2
     lowercase_constructor=$(echo $constructor | tr '[A-Z]' '[a-z]')
-    line=$(lspci | grep "$lspci_line" | head -1)
+    line=$(lspci -D | grep "$lspci_line" | head -1)
     if [ $? -ne 0 ]; then
         logging "Failed to find $constructor card with lspci"
         exit 1
     fi
 
-    card_busid=$(echo $line | cut -f 1 -d ' ' | sed -e 's/\./:/g;s/:/ /g' | awk -Wposix '{printf("PCI:%d:%d:%d\n","0x" $(NF-2), "0x" $(NF-1), "0x" $NF )}')
+    card_busid=$(echo $line | cut -f 1 -d ' ' | sed -e 's/\./:/g;s/:/ /g' | awk -Wposix '{printf("PCI:%d:%d:%d\n","0x" $2, "0x" $3, "0x" $4 )}')
     if [ $? -ne 0 ]; then
         logging "Failed to build $constructor card bus id"
         exit 1
@@ -323,25 +354,19 @@ function common_set {
 
     cat $conf | sed -e 's/PCI:X:X:X/'${card_busid}'/' > /etc/X11/xorg.conf.d/90-${lowercase_constructor}.conf
 
-    if [ "$(cat /etc/prime/current_type)" == "offload" ]; then
+    if [ "$(cat /etc/prime/current_type)" = "offload" ]; then
         nvpwr 1
         if ! lsmod | grep nvidia > /dev/null; then
             logging "Loading nvidia_modules"
             modprobe nvidia_modeset
         fi
-
-        nvidia_pci_line=$(lspci | grep "$lspci_nvidia_3d_line" | head -1)
-        if [ "$nvidia_pci_line" == "" ]; then
-            nvidia_pci_line=$(lspci | grep "$lspci_nvidia_vga_line" | head -1)
-        fi
+        # extra snippet nvidia for NVIDIA's Prime Render Offload mode
+        gpu_info=$(nvidia-xconfig --query-gpu-info 2> /dev/null)
 
         # This may easily fail, if no NVIDIA kernel module is available or alike
-        if [ "$nvidia_pci_line" != "" ]; then
-            nvidia_busid=$(echo $nvidia_pci_line | cut -f 1 -d ' ' | sed -e 's/\./:/g;s/:/ /g' | awk -Wposix '{printf("PCI:%d:%d:%d\n","0x" $(NF-2), "0x" $(NF-1), "0x" $NF )}')
-            if [ $? -ne 0 ]; then
-                echo "Failed to build NVIDIA card bus id"
-                exit 1
-            fi
+        if [ $? -eq 0 -a "$gpu_info" != "" ]; then
+            # There could be more than on NVIDIA card/GPU; use the first one in that case
+            nvidia_busid=$(echo "$gpu_info" | grep -i "PCI BusID" | head -n 1 | sed 's/PCI BusID ://' | sed 's/ //g')
             logging "Adding support for NVIDIA Prime Render Offload"
             cat $xorg_nvidia_prime_render_offload | sed -e 's/PCI:Y:Y:Y/'${nvidia_busid}'/' >> /etc/X11/xorg.conf.d/90-${lowercase_constructor}.conf
         else
@@ -349,12 +374,34 @@ function common_set {
             logging "NVIDIA Prime Render Offload not supported!"
         fi
     else
+        # https://github.com/Bumblebee-Project/bbswitch/issues/173#issuecomment-703162468
+        # ensure nvidia-persistenced and nvidia-powerd services are disabled and not running
+	# as they prevent unloading of NVIDIA modules
+     	for name in persistenced powerd
+	do
+	    if systemctl is-active --quiet nvidia-${name}.service; then
+		systemctl disable --now nvidia-${name}.service
+            fi
+	done
+        # kill all nvidia related process to fix failure to unload nvidia modules (issue#50)
+        nvidia_process=$(lsof -t /dev/nvidia* 2> /dev/null)
+        if [ -n "$nvidia_process" ]; then
+            kill -9 $nvidia_process
+        fi
+        # try only n times; avoid endless loop which may block system updates forever (boo#1173632)
+        last=3
+        for try in $(seq 1 $last); do
+            modprobe -r $nvidia_modules && break
+            if [ $try -eq $last ]; then
+                echo "NVIDIA kernel modules cannot be unloaded (tried $last times). Your machine may need a reboot."
+            fi
+        done
         nvpwr 0
     fi
 
-    #libglx_xorg=$(update-alternatives --list libglx.so | grep xorg-libglx.so)
+    libglx_xorg=$(update-alternatives --list libglx.so | grep xorg-libglx.so)
 
-    #update-alternatives --set libglx.so $libglx_xorg > /dev/null
+    update-alternatives --set libglx.so $libglx_xorg > /dev/null
 
     logging "$constructor card correctly set"
 }
@@ -377,6 +424,13 @@ function apply_current {
             current_type="nvidia"
         fi
 
+        elif [ "$current_type" == "amd"  ] && ! lspci | grep "$lspci_amd_line" > /dev/null; then
+
+            # this can happen if user set intel but changed to "Discrete only" in BIOS
+            # in that case the Intel card is not visible to the system and we must switch to nvidia
+
+            logging "Forcing nvidia due to Amd card not found"
+            current_type="nvidia"
         elif [ "$current_type" = "nvidia" ] && \
                ! lspci | grep -q "$lspci_nvidia_vga_line" && \
                ! lspci | grep -q "$lspci_nvidia_3d_line"; then
@@ -389,15 +443,12 @@ function apply_current {
             current_type="intel"
         fi
 
+
+
         if [ "$current_type" = "offload" ]; then
             offload_pref_check
             set_$(cat /etc/prime/offload_type)
-        elif [ "$current_type" = "nvidia" ]; then
-	    echo "offload" > /etc/prime/current_type
-	    offload_pref_check
-            set_$(cat /etc/prime/offload_type)
-	    echo "nvidia" > /etc/prime/current_type
-	else
+        else
             set_$current_type
         fi
     fi
@@ -427,8 +478,8 @@ function current_check {
 
 function logout_switch {
     apply_current
-    #logging "HotSwitch: starting Display Manager"
-    #systemctl start display-manager
+    logging "HotSwitch: starting Display Manager"
+    systemctl start display-manager
     logging "HotSwitch: completed!"
 }
 
@@ -443,19 +494,8 @@ function set_user {
 
 case $type in
 
-    nvidia|intel|offload|amd)
+    nvidia|intel|intel2|offload|amd)
         echo $type catched
-
-        if [ "$type" == "amd"  ] && ! lspci | grep "$lspci_amd_line" > /dev/null; then
-            echo "Amd card not found, exit..."
-            exit 1
-        fi
-
-        if [ "$type" == "intel"  ] && ! lspci | grep "$lspci_intel_line" > /dev/null; then
-            echo "Intel card not found, exit..."
-            exit 1
-        fi
-
         current_check
         check_root
 
@@ -474,6 +514,20 @@ case $type in
             #cleaning logfile if has more than 1k events
             rm $prime_logfile &> /dev/null
             echo "##DeepinPrime logfile##" > $prime_logfile
+        fi
+
+        if [ "$type" = "intel2" ];then
+            if ! rpm -q xf86-video-intel > /dev/null; then
+                echo "package xf86-video-intel is not installed";
+                exit 1
+            fi
+        fi
+
+        if [ "$type" = "amd" ];then
+            if ! rpm -q xf86-video-amdgpu > /dev/null; then
+                echo "package xf86-video-amdgpu is not installed";
+                exit 1
+            fi
         fi
 
         if ! { [ "$(bbcheck)" = "[bbswitch] NVIDIA card is ON" ] || [ "$(bbcheck)" = "[bbswitch] NVIDIA card is OFF" ]; }; then
@@ -534,16 +588,147 @@ case $type in
         echo -e "Logout to switch graphics"
     ;;
 
+    offload-set)
+
+        if [ "$2" = "intel2" ]; then
+            if ! rpm -q xf86-video-intel > /dev/null; then
+                echo "package xf86-video-intel is not installed";
+                exit 1
+            fi
+        fi
+
+        ###
+        ### no need to check for this; amdgpu/nvidia is not implemented 
+        ### for offload on AMD, only modeset/nvidia; you could run
+        ### "prime-select offload-set intel" on AMD/NVIDIA, but this is
+        ### rather confusing; so just use "prime-select offload" there for
+        ### having modeset/nvidia
+        ###
+        #if [ "$2" = "amd" ];then
+        #    if ! rpm -q xf86-video-amdgpu > /dev/null; then
+        #        echo "package xf86-video-amdgpu is not installed";
+        #        exit 1
+        #    fi
+        #fi
+
+        if ! nv_offload_capable; then
+            echo "ERROR: offloading needs nvidia drivers >= 435.xx"
+            exit 1
+        fi
+        case $2 in
+            intel|intel2)
+                echo $2 > /etc/prime/offload_type
+                echo "nvidia-offload is now available with $2 driver"
+                echo "use it with \"prime-select offload\""
+            ;;
+            *)
+                echo "Only intel|intel2 driver is available in nvidia-offload!"
+            ;;
+        esac
+    ;;
+
+    boot)
+
+        check_service
+        check_root
+
+        case $2 in
+
+            nvidia|intel|intel2|amd|last|offload)
+
+                if [ "$2" = "intel2" ]; then
+                    if ! rpm -q xf86-video-intel > /dev/null; then
+                        echo "package xf86-video-intel is not installed";
+                        exit 1
+                    fi
+                fi
+
+                if [ "$2" = "amd" ];then
+                    if ! rpm -q xf86-video-amdgpu > /dev/null; then
+                        echo "package xf86-video-amdgpu is not installed";
+                        exit 1
+                    fi
+                fi
+
+                if [ $2 = "offload" ]; then
+                    if ! nv_offload_capable; then
+                        echo "ERROR: offloading needs nvidia drivers >= 435.xx"
+                        exit 1
+                    fi
+                fi
+                echo "$2" > /etc/prime/boot
+                set_user $SUDO_USER
+                $0 get-boot
+            ;;
+
+            *)
+                echo "Invalid choice"
+                usage
+            ;;
+        esac
+    ;;
+
+    next-boot)
+
+        check_service
+        check_root
+
+        case $2 in
+
+            nvidia|intel|intel2|amd|offload)
+
+                if [ "$2" = "intel2" ]; then
+                    if ! rpm -q xf86-video-intel > /dev/null; then
+                        echo "package xf86-video-intel is not installed";
+                        exit 1
+                    fi
+                fi
+
+                if [ "$2" = "amd" ];then
+                    if ! rpm -q xf86-video-amdgpu > /dev/null; then
+                        echo "package xf86-video-amdgpu is not installed";
+                        exit 1
+                    fi
+                fi
+                if [ $2 = "offload" ]; then
+                    if ! nv_offload_capable; then
+                        echo "ERROR: offloading needs nvidia drivers >= 435.xx"
+                        exit 1
+                    fi
+                fi
+                echo "$2" > /etc/prime/forced_boot
+                set_user $SUDO_USER
+                $0 get-boot
+            ;;
+
+            abort)
+
+                if [ -f /etc/prime/forced_boot ]; then
+                    rm /etc/prime/forced_boot
+                    echo "Next boot forcing aborted"
+                else
+                    echo "Next boot is NOT forced"
+                    exit 1
+                fi
+            ;;
+
+            *)
+                echo "Invalid choice"
+                usage
+            ;;
+        esac
+    ;;
+
+
     get-current)
 
         if [ -f /etc/prime/current_type ]; then
             echo -n "Driver configured: "
             cat /etc/prime/current_type
+            bbcheck
         else
             echo "No driver configured."
-            usage
         fi
-        bbcheck
     ;;
 
     unset)
@@ -553,8 +738,8 @@ case $type in
             $0 service disable
         fi
         clean_xorg_conf_d
-        #libglx_xorg=$(update-alternatives --list libglx.so | grep xorg-libglx.so)
-        #update-alternatives --set libglx.so $libglx_xorg > /dev/null
+        libglx_xorg=$(update-alternatives --list libglx.so | grep xorg-libglx.so)
+        update-alternatives --set libglx.so $libglx_xorg > /dev/null
         rm /etc/prime/current_type &> /dev/null
         rm /etc/prime/offload_type &> /dev/null
         rm /etc/prime/boot &> /dev/null
@@ -632,11 +817,10 @@ case $type in
 
             lightdm  )
                 #lightdm_mode
-                #until [ "$(journalctl --since "$currtime" -e | grep "pam_unix(lightdm:session): session closed")" > /dev/null ]; do
-                #    sleep 0.5s
-                #done
-                #logging "user_logout_waiter: X restart detected, preparing switch to $2"
-                logging "user_logout_waiter: lightdm detected, preparing switch to $2"
+                until [ "$(journalctl --since "$currtime" -e | grep "pam_unix(lightdm.*:session): session closed")" > /dev/null ]; do
+                    sleep 0.5s
+                done
+                logging "user_logout_waiter: X restart detected, preparing switch to $2"
             ;;
 
             xdm )
@@ -659,7 +843,7 @@ case $type in
 
         echo $2 > /etc/prime/current_type
         set_user $4
-        #systemctl stop display-manager
+        systemctl stop display-manager
         #calling logout_switch or logout_switch_no_dm based on dm_func variable
         $dm_func
     ;;
@@ -716,6 +900,21 @@ case $type in
             fi
             logout_switch_no_dm
         fi
+    ;;
+
+    get-boot)
+
+        check_service
+        if [ -f /etc/prime/boot ]; then
+            echo "Default at system boot: $(cat /etc/prime/boot)"
+        else
+            echo "Default at system boot: auto (last)"
+            echo "You can configure it with prime-select boot intel|intel2|nvidia|amd|last"
+        fi
+        if [ -f /etc/prime/forced_boot ]; then
+            echo "Next boot forced to $(cat /etc/prime/forced_boot) by user"
+        fi
+
     ;;
 
     log-view)
